### ISSUE TITLE
History Monitor for Licenses not working

### ISSUE THREAD

**Issue by jtsalten** [diashenrique/iris-history-monitor#1]
Something happens with History Monitor -> License . I've just clone it and build it. I've accesed with superuser and _SYSTEM through web port, also I've open a terminal session with by default root user. In SMP, it counts the 3 licenses consumed, but in the chart it doesn't say anythin... I've been waiting 10 minutes to let the system gather statistics but still no data is displayed in that section.
![imagen](https://user-images.githubusercontent.com/6997495/64780012-acd8a780-d55f-11e9-9a0c-23ec1e9c3051.png)

![imagen](https://user-images.githubusercontent.com/6997495/64780055-be21b400-d55f-11e9-94d7-d366952883cb.png)

**Comment by diashenrique** [comment]
Hi, 
I'm sorry for the late answer. 
Did you follow the steps of this article? 

https://community.intersystems.com/post/apm-using-iris-or-cach%C3%A9-history-monitor 

First, you need to activate the History Monitor. 

The History Monitor dashboard only reads the information generated by IRIS. 

Let me know the results. 

Thanks

**Comment by diashenrique** [comment]
I'm closing the issue since I have no response since then.
