### ISSUE TITLE
Error while docker compose up

### ISSUE THREAD

**Issue by mwaseem75** [diashenrique/iris-history-monitor#10]
Hi,
I am getting below error while using docker up command:

 => ERROR [8/8] RUN     do $SYSTEM.OBJ.Load("Installer.cls", "ck")     s  1.0s 
------
 > [8/8] RUN     do $SYSTEM.OBJ.Load("Installer.cls", "ck")     set sc = ##class(App.Installer).setup()     zn "IRISMONITOR":
#12 0.743 standard_init_linux.go:228: exec user process caused: no such file or directory
------
executor failed running [/irissession.sh do $SYSTEM.OBJ.Load("Installer.cls", "ck")     set sc = ##class(App.Installer).setup()     zn "IRISMONITOR"]: exit code: 1
ERROR: Service 'iris' failed to build : Build failed
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command docker-compose -f "docker-compose.yml" up -d --build" terminated with exit code: 1.

Thanks

**Comment by diashenrique** [comment]
> Executing task: docker compose -f "docker-compose.yml" up -d --build <

[+] Building 2.1s (14/14) FINISHED                                                                                        
 => [internal] load build definition from Dockerfile                                                                 0.0s
 => => transferring dockerfile: 32B                                                                                  0.0s
 => [internal] load .dockerignore                                                                                    0.0s
 => => transferring context: 2B                                                                                      0.0s
 => [internal] load metadata for docker.io/intersystems/iris-community-arm64:2021.2.0.651.0                          1.9s
 => [auth] intersystems/iris-community-arm64:pull token for registry-1.docker.io                                     0.0s
 => [internal] load build context                                                                                    0.1s
 => => transferring context: 150.62kB                                                                                0.1s
 => [1/8] FROM docker.io/intersystems/iris-community-arm64:2021.2.0.651.0@sha256:3914e748d08e6d3427cf14a31e435a9f86  0.0s
 => CACHED [2/8] WORKDIR /opt/irisapp                                                                                0.0s
 => CACHED [3/8] RUN chown irisowner:irisowner /opt/irisapp                                                          0.0s
 => CACHED [4/8] COPY irissession.sh /                                                                               0.0s
 => CACHED [5/8] RUN chmod +x /irissession.sh                                                                        0.0s
 => CACHED [6/8] COPY  Installer.cls .                                                                               0.0s
 => CACHED [7/8] COPY  src src                                                                                       0.0s
 => CACHED [8/8] RUN     do $SYSTEM.OBJ.Load("Installer.cls", "ck")     set sc = ##class(App.Installer).setup()      0.0s
 => exporting to image                                                                                               0.0s
 => => exporting layers                                                                                              0.0s
 => => writing image sha256:3d1ef8e532601b4c344de5478128782294b8d1446cdbf63573a08f35c8ce6e39                         0.0s
 => => naming to docker.io/library/iris-history-monitor_iris                                                         0.0s
[+] Running 2/2
 ⠿ Network iris-history-monitor_default  Created                                                                     0.0s
 ⠿ Container iris-history-monitor        Started                                                                     0.6s

Terminal will be reused by tasks, press any key to close it.
