### ISSUE TITLE
Como importar em um ambiente Windows Server

### ISSUE THREAD

**Issue by wjuniorbhz** [diashenrique/iris-history-monitor#2]
Henrique, tenho um ambiente IRIS rodando em Windows, como fazer a importação deste monitoramento?
Obrigado

**Comment by diashenrique** [comment]
Você pode seguir as recomendações que deixei neste comentário aqui, no link abaixo a questão era para um ambiente que não utiliza docker. Mas você seguindo o procedimento, pode implementar no seu ambiente sem problemas

https://community.intersystems.com/post/dashboard-iris-history-monitor#comment-73721
